{% if ansible_distribution == 'MacOSX' %}
# Source global zprofile to set initial PATH
source /etc/zprofile
{% endif %}

# Source files in $HOME/.zshrc.d/
zshrc_d="$HOME/.zshrc.d/"
if [ -d $zshrc_d ]; then
    for file in $zshrc_d/*.zsh; do
        source $file;
    done
fi

# Ansible-managed

{% if 'work' in inventory_hostname_short %}
# Intel proxy
export https_proxy="http://proxy-chain.intel.com:912"
export http_proxy=$https_proxy
{% endif %}

# zsh-syntax-highlighting must be at end of zshrc
source \
{% if ansible_distribution == 'Archlinux' %}
  /usr/share/zsh/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
{% elif ansible_distribution == 'MacOSX' %}
  /usr/local/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
{% endif %}

