# Source files in $HOME/.zshrc.d/
zshrc_d="$HOME/.zshrc.d/"
if [ -d $zshrc_d ]; then
    for file in $zshrc_d/*.zsh; do
        source $file;
    done
fi

# Ansible-managed

# zsh-syntax-highlighting must be at end of zshrc
source \
{% if ansible_distribution == 'Archlinux' %}
  /usr/share/zsh/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
{% elif ansible_distribution == 'MacOSX' %}
  /usr/local/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
{% endif %}

