# Start X on login to virtual console
[ -z "$DISPLAY" ] && [ "$XDG_VTNR" -eq 1 ] && \

  # See xserver(1)
  exec startx -- \
    -ardelay {{ zprofile.repeat_delay }} \
    -arinterval {{ zprofile.repeat_interval }} \
{% if dpi is defined %}
    -dpi {{ dpi }}
{% endif %}

# Use gpg-agent as SSH agent
# Taken from gpg-agent(1) - set SSH agent socket
if [ "${gnupg_SSH_AUTH_SOCK_by:-0}" -ne $$ ]; then
    export SSH_AUTH_SOCK="$(gpgconf --list-dirs agent-ssh-socket)"
fi

