# Start X on login to virtual console
[ -z "$DISPLAY" ] && [ "$XDG_VTNR" -eq 1 ] && \

  # See xserver(1)
  exec startx -- \
    -ardelay {{ zprofile.repeat_delay }} \
    -arinterval {{ zprofile.repeat_interval }}
